version: "3.4"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME: root
      - MONGO_INITDB_ROOT_PASSWORD: password
      - MONGO_INITDB_DATABASE: menu-service
    volumes:
      - ./docker/mongodb/data:/data:db




